name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - id: sdk-version
        run: |
          echo "version=$(curl -s https://api.github.com/repos/joseluisq/macosx-sdks/releases/latest | jq -r .tag_name)" | tee -a $GITHUB_OUTPUT

      - name: Download MacOS SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          curl -OsL https://github.com/joseluisq/macosx-sdks/releases/download/${{ steps.sdk-version.outputs.version }}/MacOSX${{ steps.sdk-version.outputs.version }}.sdk.tar.xz
          tar xf MacOSX${{ steps.sdk-version.outputs.version }}.sdk.tar.xz
          mv MacOSX${{ steps.sdk-version.outputs.version }}.sdk ../sdk
          rm MacOSX${{ steps.sdk-version.outputs.version }}.sdk.tar.xz
          pwd

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
